---
services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homiebridge
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      #- PLEX_CLAIM= # Uncomment this to setup Plex server, get your claim code from here - https://www.plex.tv/claim/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./plexmediaserver:/config
      - ./plexmediaserver/tv:/mnt/tv
      - ./plexmediaserver/movies:/mnt/movies
      - ./plexmediaserver/music:/mnt/music
      - ./plexmediaserver/transcode:/mnt/transcode
    restart: unless-stopped
