---
services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homiebridge
    restart: unless-stopped
    network_mode: host
    volumes:
      - /srv/containers/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      #- PLEX_CLAIM= # Uncomment this to setup Plex server, get your claim code from here - https://www.plex.tv/claim/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/containers/plexmediaserver:/config
      - /srv/containers/plexmediaserver/transcode:/transcode
      - /media/jonathan/Downloads:/mnt
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - /srv/containers/transmission:/config
      - /media/jonathan/Downloads:/downloads
      - /media/jonathan/Downloads:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
