- name: Bootstrap Raspberry Pi homelab
  hosts: homelab
  become: true

  vars:
    repo_url: "https://github.com/JonathanSeriesX/homelab.git"
    repo_dest: "~/homelab"
    docker_add_repo: true
    docker_users:
      - jonathan
    drive_uuid: "d67323ef-b79f-451a-b623-e94a717e87bb"

  pre_tasks:
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
      tags: update

  roles:
    - geerlingguy.docker

  tasks:
    - name: Ensure cgroup flags on kernel cmdline
      become: true
      ansible.builtin.replace:
        path: /boot/firmware/cmdline.txt
        regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
        replace: '\1 {{ item }}'
      with_items:
        - "cgroup_enable=cpuset"
        - "cgroup_memory=1"
        - "cgroup_enable=memory"
      register: cmdline_edit

    - name: Reboot if cmdline changed
      become: true
      ansible.builtin.reboot:
        reboot_timeout: 600
      when: cmdline_edit is changed

    - name: Clone or update homelab repo
      become: false
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: main
        accept_hostkey: yes
        update: yes
      register: git_result

    - name: Mount Downloads drive
      become: true
      ansible.posix.mount:
        path: /media/jonathan/Downloads
        src: "{{ drive_uuid }}"
        fstype: ext4
        opts: defaults,noatime,nofail
        state: mounted

    - name: Bring up Docker Compose stack
      become: false
      community.docker.docker_compose_v2:
        project_src: "{{ repo_dest }}"
        state: present
        pull: always
        remove_orphans: yes
        recreate: auto
