- name: Setup HomeBridge + Plex
  hosts: media-server
  become: true

  tasks:
    - name: Install Docker and Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Start services via docker-compose
      command: docker-compose up -d
      #args:
      #  chdir:
# WIP
