- hosts: pis
  roles:
    - geerlingguy.docker
  become: true
  tasks:
    # something something docker install
    - name: Clone homelab
      become: false
      git:
        repo: "git@github.com:you/homelab.git"
        dest: /srv/homelab
        version: main
        accept_hostkey: yes

    - name: Docker compose up
      become: false
      shell: |
        cd /srv/homelab
        docker compose pull || true
        docker compose up -d
